namespace LoggingWeaving.Internal;

internal static class GeneratedAttributeSource
{
    internal const string Text = """
        // <auto-generated />
        #nullable enable

        namespace LoggingWeaving;

        internal enum LoggingGuardMode
        {
            Disabled = 0,
            Enabled = 1
        }

        [global::System.AttributeUsage(
            global::System.AttributeTargets.Assembly |
            global::System.AttributeTargets.Class |
            global::System.AttributeTargets.Struct |
            global::System.AttributeTargets.Method,
            AllowMultiple = false,
            Inherited = false)]
        internal sealed class LoggingGuardAttribute : global::System.Attribute
        {
            internal LoggingGuardAttribute(LoggingGuardMode mode)
            {
                Mode = mode;
            }

            internal LoggingGuardMode Mode { get; }
        }
        """;
}
