<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <LoggingWeavingBuildHostPath>$([System.IO.Path]::GetFullPath('$([System.IO.Path]::Combine($(MSBuildProjectDirectory), '..', '..', 'src', 'LoggingWeaving.BuildHost', 'bin', $(Configuration), 'net8.0', 'LoggingWeaving.BuildHost.dll'))'))</LoggingWeavingBuildHostPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
    <Compile Include="..\Shared\NetStandardLoggingCase.cs" Link="NetStandardLoggingCase.cs" />
    <ProjectReference Include="..\..\src\LoggingWeaving.Generator\LoggingWeaving.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\src\LoggingWeaving.BuildHost\LoggingWeaving.BuildHost.csproj" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" GlobalPropertiesToRemove="TargetFramework" />
  </ItemGroup>

  <Import Project="..\..\build\LoggingWeaving.props" />
  <Import Project="..\..\build\LoggingWeaving.targets" />

</Project>
